### ISSUE TITLE
Add support for Floodgate Bedrock UUIDs

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [nichogx/DiscordRoleSync#14]
The plugin is not compatible on my cross-platform Minecraft server as the plugin doesn't accept Floodgate UUIDs. It would be much better if you consider adding Floodgate Bedrock UUID support for this plugin.

**Comment by nichogx** [comment]
This is a Java only plugin, Bedrock is not supported, since we use Mojang usernames to get the UUID from their API.
You could manually link the user in the database if you know their UUID, and it should work.

**Comment by Tim203** [comment]
We offer an API endpoint to get the xuid of a player from an username (https://api.geysermc.org/v2/xbox/xuid/*gamertag*) if you're interested in adding Bedrock support. You can convert a xuid to an uuid by setting the most significant bits to 0 and the least significant bits to the xuid.
But since it appears that this project doesn't offer a standalone version, you can also use the Floodgate API [FloodgateApi#getUuidFor(String)](https://github.com/GeyserMC/Floodgate/blob/master/api/src/main/java/org/geysermc/floodgate/api/FloodgateApi.java#L118) and let it do everything for you.

**Comment by nichogx** [comment]
Thanks @Tim203, I will take a look when I have a chance! Lots of people have been asking about bedrock support.

**Comment by BannerGames** [comment]
> We offer an API endpoint to get the xuid of a player from an username (https://api.geysermc.org/v2/xbox/xuid/*gamertag*) if you're interested in adding Bedrock support. You can convert a xuid to an uuid by setting the most significant bits to 0 and the least significant bits to the xuid. But since it appears that this project doesn't offer a standalone version, you can also use the Floodgate API [FloodgateApi#getUuidFor(String)](https://github.com/GeyserMC/Floodgate/blob/master/api/src/main/java/org/geysermc/floodgate/api/FloodgateApi.java#L118) and let it do everything for you.

Is the Geyser API working? I'm trying to access but it returns "{"message":"The Xbox Api isn't setup correctly. Please contact a GeyserMC developer"}".

**Comment by GeleVla** [comment]
Any update on this?

**Comment by nichogx** [comment]
This plugin is no longer under development by me, but is open source in case anyone wants to take a look at it and add this functionality.

**Comment by nichogx** [comment]
Experimental Geyser support has been added in `2.0.0-rc.4`. This project has been moved to GitLab. Please open another issue there if there are more related requests!

Project: https://gitlab.com/nichogx/DiscordRoleSync
2.0.0-rc.4: https://gitlab.com/nichogx/DiscordRoleSync/-/packages/26935365
